export const sampleData: ExtendedCrowdData[] = [
  {
    risk_level: "High",
    risk_trend: "Increasing",
    hot_zones: [
      "0_0",
      "0_1",
      "0_2",
      "1_0",
      "1_1",
      "1_2",
      "2_2",
      "3_0",
      "3_2",
    ],
    time_stamp: "2024-06-21T14:30:00.000Z",
    image: "./backend/data/test_video_4k.mp4",
    summary: "The overall threat assessment indicates a high level of risk across multiple zones due to high crowd densities and potential bottlenecks. Immediate action is required to mitigate these risks, including crowd dispersal measures, enhanced surveillance, and deployment of additional security personnel. A comprehensive review of event planning and site layout is necessary to prevent similar risks in future events.",
    insights: "Crowd crush risk, Exit blockage, Security deployment needed",
    flags: [
      "EMERGENCY CROWD - CRUSH RISK",
      "HIGH DENSITY",
    ],
    protocol: "Implement crowd dispersal measures, enhance surveillance and monitoring, deploy additional security personnel, review and adjust event schedules, and conduct a thorough review of site layout and event planning.",
    frame_summary: "The overall threat assessment indicates a high level of risk across multiple zones due to high crowd densities and potential bottlenecks. Immediate action is required to mitigate these risks, including crowd dispersal measures, enhanced surveillance, and deployment of additional security personnel. A comprehensive review of event planning and site layout is necessary to prevent similar risks in future events.",
  },
  {
    risk_level: "High",
    risk_trend: "Increasing",
    hot_zones: [
      "Zone 1_2",
      "Zone 2_0",
      "Zone 3_0",
      "Zone 3_2",
    ],
    time_stamp: "2024-06-21T14:30:00.001Z",
    image: "./backend/data/test_video_4k.mp4",
    summary: "The overall threat assessment indicates a high level of risk due to overcrowding and poor crowd distribution across multiple zones. Immediate intervention is required to manage crowd density, improve infrastructure, and enhance emergency response planning. Continuous monitoring and adaptive management strategies are crucial to mitigate risks and ensure a safe environment for attendees. Several zones exhibit crowd densities significantly higher than recommended limits.",
    insights: "Crowd crush risk in Zone 1_2 and Zone 2_0, Exit blockage risk due to high crowd density, Security deployment needed in high-risk zones, Inadequate sanitary provision in Zone 0_1",
    flags: [
      "EMERGENCY CROWD - CRUSH RISK",
      "HIGH DENSITY",
    ],
    protocol: "Deploy additional crowd management personnel, implement crowd control measures, enhance surveillance, and review site layouts to improve crowd distribution.",
    frame_summary: "The overall threat assessment indicates a high level of risk due to overcrowding and poor crowd distribution across multiple zones. Immediate intervention is required to manage crowd density, improve infrastructure, and enhance emergency response planning. Continuous monitoring and adaptive management strategies are crucial to mitigate risks and ensure a safe environment for attendees. Several zones exhibit crowd densities significantly higher than recommended limits.",
  },
  {
    risk_level: "High",
    risk_trend: "Increasing",
    hot_zones: [
      "0_2",
      "0_3",
      "1_3",
      "3_2",
    ],
    time_stamp: "2024-06-21T14:30:00.002Z",
    image: "./backend/data/test_video_4k.mp4",
    summary: "The night market event is experiencing high crowd densities in several zones, exceeding recommended limits and posing a high risk of crowd-related incidents. Continuous monitoring and crowd management are necessary to mitigate these risks. Potential bottlenecks and directional conflicts have been identified in multiple zones. Emergency response planning and staff training are also crucial to ensure a safe and enjoyable experience for attendees. The overall threat assessment is Moderate to High.",
    insights: "Crowd crush risk in Zones 0_2, 0_3, 1_3, and 3_2, Potential bottlenecks in Zones 2_1, 2_3, and 3_1, Inadequate crowd management in several zones, Insufficient emergency response planning",
    flags: [
      "**HIGH DENSITY**",
      "**CROWD CRUSH RISK**",
    ],
    protocol: "Implement crowd control measures and surveillance in high-risk zones, develop and update emergency response plans, and provide regular training to staff on crowd management and emergency response.",
    frame_summary: "The night market event is experiencing high crowd densities in several zones, exceeding recommended limits and posing a high risk of crowd-related incidents. Continuous monitoring and crowd management are necessary to mitigate these risks. Potential bottlenecks and directional conflicts have been identified in multiple zones. Emergency response planning and staff training are also crucial to ensure a safe and enjoyable experience for attendees. The overall threat assessment is Moderate to High.",
  },
  {
    risk_level: "High",
    risk_trend: "Increasing",
    hot_zones: [
      "1_1",
      "1_2",
      "1_3",
    ],
    time_stamp: "2024-06-21T14:30:00.003Z",
    image: "./backend/data/test_video_4k.mp4",
    summary: "The crowd situation indicates a high risk level due to overcrowding in Zone 1_1 and moderate to high densities in several other zones. Potential risks include crowd crush, bottlenecks, and directional conflicts. Immediate action is required to manage crowd density and prevent safety incidents. Enhanced monitoring and crowd management strategies are necessary. The situation is being closely monitored.",
    insights: "Crowd crush risk in Zone 1_1, Potential bottlenecks in Zones 1_2 and 1_3, Need for enhanced security deployment",
    flags: [
      "**EMERGENCY CROWD - CRUSH RISK**",
      "**HIGH DENSITY**",
    ],
    protocol: "Implement immediate crowd control measures in Zone 1_1, enhance monitoring across all zones, and adjust event layout or crowd management strategies as necessary. Ensure clear communication channels and define emergency response plans.",
    frame_summary: "The crowd situation indicates a high risk level due to overcrowding in Zone 1_1 and moderate to high densities in several other zones. Potential risks include crowd crush, bottlenecks, and directional conflicts. Immediate action is required to manage crowd density and prevent safety incidents. Enhanced monitoring and crowd management strategies are necessary. The situation is being closely monitored.",
  },
  {
    risk_level: "High",
    risk_trend: "Increasing",
    hot_zones: [
      "1_2",
      "2_0",
      "2_2",
    ],
    time_stamp: "2024-06-21T14:30:00.004Z",
    image: "./backend/data/test_video_4k.mp4",
    summary: "The crowd situation is critical with high densities in zones 1_2, 2_0, and 2_2, posing significant safety risks. Several zones are at or beyond recommended risk thresholds for crowd density and movement patterns. The overall risk level is high due to overcrowding, inadequate emergency planning, and insufficient crowd management. Immediate interventions are required to mitigate these risks. The situation is being closely monitored.",
    insights: "Crowd crush risk in zone 1_2, Exit blockage potential in zones with complex layouts, Security deployment needed in high-risk zones",
    flags: [
      "**EMERGENCY CROWD - CRUSH RISK**",
      "**HIGH DENSITY**",
    ],
    protocol: "Deploy additional stewards/crowd marshals to manage crowd density and flow, enhance surveillance in high-risk zones, implement crowd control measures, and develop comprehensive emergency response plans including evacuation procedures and first aid response.",
    frame_summary: "The crowd situation is critical with high densities in zones 1_2, 2_0, and 2_2, posing significant safety risks. Several zones are at or beyond recommended risk thresholds for crowd density and movement patterns. The overall risk level is high due to overcrowding, inadequate emergency planning, and insufficient crowd management. Immediate interventions are required to mitigate these risks. The situation is being closely monitored.",
  },
  {
    risk_level: "High",
    risk_trend: "Increasing",
    hot_zones: [
      "0_2",
      "1_2",
      "2_0",
      "2_1",
      "2_2",
      "2_3",
      "3_3",
    ],
    time_stamp: "2024-06-21T14:30:00.006Z",
    image: "./backend/data/test_video_4k.mp4",
    summary: "The overall threat assessment indicates a high level of risk across multiple zones due to overcrowding and potential bottlenecks. Immediate interventions are required in high-risk zones to prevent crowd disasters. Continuous monitoring and crowd management strategies are essential across all zones. High crowd densities in adjacent zones can lead to cascade risks.",
    insights: "Crowd crush risk in zones 0_2, 1_2, 2_0, 2_2, 2_3, 3_3, Exit blockage potential in zones 1_2, 2_2, Security deployment needed in zones 1_2, 2_0, 2_1, 2_2, 2_3",
    flags: [
      "**EMERGENCY CROWD - CRUSH RISK**",
      "**HIGH DENSITY**",
    ],
    protocol: "Implement crowd dispersal and control measures in high-risk zones, enhance surveillance and monitoring across all zones, develop and communicate emergency response plans, ensure clear escape routes and emergency access.",
    frame_summary: "The overall threat assessment indicates a high level of risk across multiple zones due to overcrowding and potential bottlenecks. Immediate interventions are required in high-risk zones to prevent crowd disasters. Continuous monitoring and crowd management strategies are essential across all zones. High crowd densities in adjacent zones can lead to cascade risks.",
  },
  {
    risk_level: "High",
    risk_trend: "Increasing",
    hot_zones: [
      "0_2",
      "1_1",
      "1_2",
      "2_1",
    ],
    time_stamp: "2024-06-21T14:30:00.007Z",
    image: "./backend/data/test_video_4k.mp4",
    summary: "The overall threat assessment indicates a high risk level across the event area due to overcrowding, crowd pressure, and potential bottlenecks in multiple zones. Continuous monitoring and crowd management are critical. Several zones exceed recommended crowd density thresholds, violating safety guidelines. Emergency response planning and training are essential to mitigate these risks.",
    insights: "Crowd crush risk in zones 0_2, 1_1, 1_2, Exit blockage potential in zones 2_0, 3_0, Security deployment needed in high-risk zones",
    flags: [
      "**HIGH DENSITY**",
      "**CROWD CRUSH RISK**",
    ],
    protocol: "Implement crowd management strategies across all zones, enhance surveillance and monitoring, develop comprehensive emergency response plans, and conduct regular training and drills for emergency responders.",
    frame_summary: "The overall threat assessment indicates a high risk level across the event area due to overcrowding, crowd pressure, and potential bottlenecks in multiple zones. Continuous monitoring and crowd management are critical. Several zones exceed recommended crowd density thresholds, violating safety guidelines. Emergency response planning and training are essential to mitigate these risks.",
  },
  {
    risk_level: "High",
    risk_trend: "Increasing",
    hot_zones: [
      "1_0",
      "2_0",
      "2_3",
    ],
    time_stamp: "2024-06-21T14:30:00.008Z",
    image: "./backend/data/test_video_4k.mp4",
    summary: "The crowd density in several zones exceeds recommended limits, posing a high risk to safety. Zones 1_0, 2_0, and 2_3 are of particular concern. Immediate intervention is required to mitigate potential safety risks. Moderate-risk zones require continuous monitoring and preparedness for intervention. Crowd control measures and enhanced surveillance are recommended.",
    insights: "Crowd crush risk in Zones 1_0, 2_0, and 2_3, Potential exit blockage in high-density zones, Security deployment needed in Zones 1_0, 2_0, and 2_3",
    flags: [
      "**EMERGENCY CROWD - CRUSH RISK**",
      "**HIGH DENSITY**",
    ],
    protocol: "Implement crowd control measures, enhance surveillance, and establish clear communication channels between event staff, security, and emergency services. Prioritize Zones 1_0, 2_0, and 2_3 for immediate intervention.",
    frame_summary: "The crowd density in several zones exceeds recommended limits, posing a high risk to safety. Zones 1_0, 2_0, and 2_3 are of particular concern. Immediate intervention is required to mitigate potential safety risks. Moderate-risk zones require continuous monitoring and preparedness for intervention. Crowd control measures and enhanced surveillance are recommended.",
  },
  {
    risk_level: "High",
    risk_trend: "Increasing",
    hot_zones: [
      "0_0",
      "0_1",
      "1_3",
      "2_0",
      "3_2",
      "3_3",
    ],
    time_stamp: "2024-06-21T14:30:00.009Z",
    image: "./backend/data/test_video_4k.mp4",
    summary: "The overall threat assessment indicates a high risk of overcrowding and crowd disasters in multiple zones. Immediate intervention is required to manage crowd densities, prevent bottlenecks, and ensure safe escape routes. Continuous monitoring and coordination between zones are essential to mitigate risks and prevent a cascade of emergencies. High crowd densities are observed in zones 0_0, 0_1, 1_3, 2_0, 3_2, and 3_3.",
    insights: "Crowd crush risk, Exit blockage, Security deployment needed",
    flags: [
      "EMERGENCY CROWD - CRUSH RISK",
      "HIGH DENSITY",
    ],
    protocol: "Initiate crowd dispersal and restrict entry to high-risk zones. Enhance surveillance and monitoring. Implement crowd control measures and deploy additional personnel. Review and adjust site layouts, develop emergency response plans, and conduct training.",
    frame_summary: "The overall threat assessment indicates a high risk of overcrowding and crowd disasters in multiple zones. Immediate intervention is required to manage crowd densities, prevent bottlenecks, and ensure safe escape routes. Continuous monitoring and coordination between zones are essential to mitigate risks and prevent a cascade of emergencies. High crowd densities are observed in zones 0_0, 0_1, 1_3, 2_0, 3_2, and 3_3.",
  },
  {
    risk_level: "High",
    risk_trend: "Increasing",
    hot_zones: [
      "1_0",
      "1_3",
      "2_1",
      "3_1",
    ],
    time_stamp: "2024-06-21T14:30:00.010Z",
    image: "./backend/data/test_video_4k.mp4",
    summary: "The overall risk assessment indicates a high likelihood of crowd-related incidents due to extremely high densities in Zones 1_0 and 1_3, and moderate to high densities in other zones. Immediate intervention is required to manage crowd density and enhance surveillance. Emergency response plans should be activated, and additional security personnel deployed to high-risk areas. Continuous monitoring of crowd movement and density is crucial to prevent overcrowding and potential bottlenecks.",
    insights: "Crowd crush risk in Zones 1_0 and 1_3, Potential bottlenecks in Zones 2_1 and 3_1, Need for enhanced surveillance and security deployment, Risk of directional conflicts in Zones 0_1 and 3_3",
    flags: [
      "**EMERGENCY CROWD - CRUSH RISK**",
      "**HIGH DENSITY**",
    ],
    protocol: "Implement emergency response plans, enhance crowd monitoring and management, ensure clear emergency access routes, and deploy additional security personnel to high-risk zones.",
    frame_summary: "The overall risk assessment indicates a high likelihood of crowd-related incidents due to extremely high densities in Zones 1_0 and 1_3, and moderate to high densities in other zones. Immediate intervention is required to manage crowd density and enhance surveillance. Emergency response plans should be activated, and additional security personnel deployed to high-risk areas. Continuous monitoring of crowd movement and density is crucial to prevent overcrowding and potential bottlenecks.",
  },
  {
    risk_level: "High",
    risk_trend: "Increasing",
    hot_zones: [
      "0_0",
      "1_1",
      "3_2",
    ],
    time_stamp: "2024-06-21T14:30:00.012Z",
    image: "./backend/data/test_video_4k.mp4",
    summary: "The overall risk assessment is Moderate to High due to observed crowd densities and potential bottlenecks. Zones 0_0, 1_1, and 3_2 are of particular concern due to high crowd densities and potential overcrowding. Immediate attention is required to manage crowd distribution and prevent overcrowding. Potential infrastructure risks and inadequate facilities have been identified in several zones. Enhanced monitoring and crowd management strategies are necessary to mitigate risks.",
    insights: "Crowd crush risk in zones 0_0, 1_1, and 3_2, Exit blockage potential in zones 1_1 and 3_2, Security deployment needed in high-risk zones, Insufficient toilet facilities in zone 1_2",
    flags: [
      "EMERGENCY CROWD - CRUSH RISK",
      "HIGH DENSITY",
    ],
    protocol: "Deploy additional crowd management personnel to high-risk zones, improve signage in zones with potential bottlenecks, and enhance surveillance in high-risk zones. Establish clear communication channels and define emergency response procedures. Continuously monitor crowd densities and distribution in high-risk zones.",
    frame_summary: "The overall risk assessment is Moderate to High due to observed crowd densities and potential bottlenecks. Zones 0_0, 1_1, and 3_2 are of particular concern due to high crowd densities and potential overcrowding. Immediate attention is required to manage crowd distribution and prevent overcrowding. Potential infrastructure risks and inadequate facilities have been identified in several zones. Enhanced monitoring and crowd management strategies are necessary to mitigate risks.",
  },
  {
    risk_level: "High",
    risk_trend: "Increasing",
    hot_zones: [
      "0_2",
      "1_2",
      "2_0",
      "2_2",
      "3_1",
    ],
    time_stamp: "2024-06-21T14:30:00.013Z",
    image: "./backend/data/test_video_4k.mp4",
    summary: "The overall threat assessment indicates a high risk level due to multiple zones with high crowd densities and potential bottlenecks. Immediate intervention is required to mitigate these risks. Continuous monitoring and coordinated crowd management strategies across zones are crucial to ensuring safety.",
    insights: "Crowd crush risk in zones 0_2 and 1_2, Exit blockage potential in zones 2_0 and 2_2, Security deployment needed in high-risk zones",
    flags: [
      "EMERGENCY CROWD - CRUSH RISK",
      "HIGH DENSITY",
    ],
    protocol: "Deploy additional security personnel to high-risk zones, enhance surveillance, implement crowd control measures, and develop/update emergency response plans.",
    frame_summary: "The overall threat assessment indicates a high risk level due to multiple zones with high crowd densities and potential bottlenecks. Immediate intervention is required to mitigate these risks. Continuous monitoring and coordinated crowd management strategies across zones are crucial to ensuring safety.",
  },
  {
    risk_level: "High",
    risk_trend: "Increasing",
    hot_zones: [
      "0_1",
      "1_1",
      "2_2",
      "3_2",
    ],
    time_stamp: "2024-06-21T14:30:00.014Z",
    image: "./backend/data/test_video_4k.mp4",
    summary: "The overall threat assessment indicates a moderate to high risk level across multiple zones due to overcrowding, potential bottlenecks, and infrastructure risks. Critical intervention requirements include increasing crowd monitoring, implementing crowd control measures, and reviewing emergency response plans. Continuous monitoring and follow-up are necessary to ensure crowd safety.",
    insights: "Crowd crush risk in zones 0_1, 1_1, 2_2, and 3_2, Exit blockage potential in zones 2_2 and 3_2, Security deployment needed in zones with potential bottlenecks",
    flags: [
      "**EMERGENCY CROWD - CRUSH RISK**",
      "**HIGH DENSITY**",
    ],
    protocol: "Implement crowd monitoring and control measures, review and update emergency response plans, and revise the overall event plan to manage crowd density effectively.",
    frame_summary: "The overall threat assessment indicates a moderate to high risk level across multiple zones due to overcrowding, potential bottlenecks, and infrastructure risks. Critical intervention requirements include increasing crowd monitoring, implementing crowd control measures, and reviewing emergency response plans. Continuous monitoring and follow-up are necessary to ensure crowd safety.",
  },
  {
    risk_level: "High",
    risk_trend: "Increasing",
    hot_zones: [
      "0_1",
      "2_0",
      "2_1",
      "2_3",
    ],
    time_stamp: "2024-06-21T14:30:00.015Z",
    image: "./backend/data/test_video_4k.mp4",
    summary: "The overall threat assessment indicates a high level of risk across multiple zones due to excessive crowd density, potential bottlenecks, and infrastructure risks. Immediate intervention is required in zones like 0_1, 2_0, 2_1, and 2_3 to prevent potential crowd disasters. Continuous monitoring and crowd management strategies are necessary across all zones to ensure a safe environment.",
    insights: "Crowd crush risk, Exit blockage, Security deployment needed",
    flags: [
      "EMERGENCY CROWD - CRUSH RISK",
      "HIGH DENSITY",
    ],
    protocol: "Deploy additional security personnel to manage and disperse crowds in high-risk zones, ensure clear escape routes, and enhance surveillance.",
    frame_summary: "The overall threat assessment indicates a high level of risk across multiple zones due to excessive crowd density, potential bottlenecks, and infrastructure risks. Immediate intervention is required in zones like 0_1, 2_0, 2_1, and 2_3 to prevent potential crowd disasters. Continuous monitoring and crowd management strategies are necessary across all zones to ensure a safe environment.",
  },
  {
    risk_level: "High",
    risk_trend: "Increasing",
    hot_zones: [
      "Zone 0_0",
      "Zone 0_1",
      "Zone 1_0",
    ],
    time_stamp: "2024-06-21T14:30:00.016Z",
    image: "./backend/data/test_video_4k.mp4",
    summary: "The crowd density in several zones exceeds recommended safety guidelines, posing a significant risk of overcrowding and crowd crush. Zone 0_0 is at critical risk, while Zone 0_1 and Zone 1_0 are at high risk. Zone 0_3 is at moderate to high risk. Immediate crowd control measures are necessary.",
    insights: "Crowd crush risk in Zone 0_0, Exit blockage risk in Zone 0_1 and Zone 1_0, Security deployment needed in high-risk zones",
    flags: [
      "**EMERGENCY CROWD - CRUSH RISK**",
      "**HIGH DENSITY**",
    ],
    protocol: "Implement crowd control barriers, redirect crowd flow, increase security and medical personnel presence, enhance surveillance and monitoring, and establish clear communication channels for emergency response.",
    frame_summary: "The crowd density in several zones exceeds recommended safety guidelines, posing a significant risk of overcrowding and crowd crush. Zone 0_0 is at critical risk, while Zone 0_1 and Zone 1_0 are at high risk. Zone 0_3 is at moderate to high risk. Immediate crowd control measures are necessary.",
  },
];